### PR TITLE
Nonlinear regression convergence results

### PR DESCRIPTION
**Pull request by gkronber**
This PR includes several improvements:
1. NLR uses the new ParameterOptimizer based on the native interpreter with improved performance
2. Removed all usages of obsolete classes in NLR.
3. Produce the number of function and Jacobian evaluations as an additional result for debugging convergence problems in NLR.

### CODE REVIEW

**Review by mkommend — CHANGES_REQUESTED** [review]
Changes look good. 

A possible bug is in the ```OptimizeParameters```method, cause if the parameters in the tree are not updated (condition on line 233) although the optimization has been successful the MSE is calculated with the previous parameters. Maybe it is better to remove the feature of not updating parameters.

However, by the changes in the ```ParameterOptimizationEvaluator``` using the native interpreter, parameter optimization and quality calculation is now independent. Therefore, I would additionally remove the MSE calculation from the ```OptimizerParameters``` method and calculate the quality independently.

**Comment by gkronber** [comment]
Thank you for the improvment suggestions. I implemented all three:
* Do not refer to TreeToAutoDiffTermConverter and instead use the supported symbols in ParameterOptimizer, which is used in the evaluator
* Extracted MSE calculation out of OptimizeParameters method.
* Removed the functionality to calculate the MSE for optimized parameters without updating parameters

**Review by mkommend — APPROVED** [review]

**Review by mkommend — APPROVED** [review]
I have approved this changes. 

@gkronber Please review these small updates (reordering of methods, reuse of evaluate method for quality calculation). I cannot assign this PR for you to review as you have opened the PR.

**Comment by gkronber** [comment]
Reviewed 5d75202. Thanks.

**Pull request merged**
