### PR TITLE
GUI flickers and is locked if GrammarView is shown and a new problem (data) is loaded

### PR DESCRIPTION
**Pull request by mkommend**

### CODE REVIEW

**Comment by NimZwei** [comment]
Flickering is indeed gone and solved by invoking the updates on the correct thread. Thanks a lot!


However, the View for the selected symbol is not correctly updated when the symbol was configured manually.
But the described issues are not introduced in this PR but are also present in main.

Example to reproduce the issues: Create a new Sym Reg Problem, select the Korns 1 instance, view the grammar and select the Variable symbol.
With this setup, two bugs can now be observed:
- First, when deselecting the X0 variable by clicking the checkbox, sometimes nothing happens, sometimes a different variable is deselected. Additionally, the target Y is selected, which should not be available for the variable symbol (because it is the target). Since this is behavior is not deterministic, I suspect that there is a race condition somewhere during the view updates.
- Second, after deselecting variables X0, X1 and X2, when the instance is now changed to, for instance Nguyen F1, the view does not update and still show the variables from the Korns 1 instance.

Curiously, both issues do not happen if the variable symbol is only viewed without making any changes (e.g. deselecting variables). Therefore, I suspect that it has to do with some updates the grammar fires when the symbol configuration changes.

**Comment by mkommend** [comment]
> * First, when deselecting the X0 variable by clicking the checkbox, sometimes nothing happens, sometimes a different variable is deselected. Additionally, the target Y is selected, which should not be available for the variable symbol (because it is the target). Since this is behavior is not deterministic, I suspect that there is a race condition somewhere during the view updates.

This behavior was indeed a bug and fixed with 09ec62e2deea7b1b4762ff94d7480cddb35d0511.

**Comment by mkommend** [comment]
> * Second, after deselecting variables X0, X1 and X2, when the instance is now changed to, for instance Nguyen F1, the view does not update and still show the variables from the Korns 1 instance.

This behavior is intended, though somewhat counter intuitive. Whenever a symbol is manually adapted, its internal state is set to fixed and it is no longer automatically updated and adapted, e.g. the variable names are not synced with the ones in the problem data.

**Review by NimZwei — APPROVED** [review]
As discussed with @mkommend, the behavior is a bit unintuitive, since the GUI does not show that deselecting variables in the variable symbol causes the symbol to be "fixed", which then excludes the symbol from being updated when the problem instance changes. But this is by design, so the changes fix the described issues.

**Pull request merged**
